# Configuration file with default values

# Debug and info settings
debug_01: false                          # Set to true to enable debug prints and visualisations
AddInfo: false                           # Set to true to enable additional info prints of the processing
GetInfo: true                            # Set to true to enable detailed info files
GetImages: false                          # Set to true to enable images with contour and landmarks drawn as output
GetContour: false                         # Set to true to enable output of contour points as CSV

# Processing settings
DefinedFile: "all"                       # Set to specific image name (without extension) e.g. "CC21L003" or "all"
Fast_Mode: false                         # true = lose slightly on accuracy for faster processing - test for your dataset
Keep_landmarks_as_anchors: true          # If false, the landmark will be moved to the closest contour point
Number_of_worst_performers_review: 5     # How many worst performing images to be reviewed as CSV

# Paths
PROJECT_DIR: "/storage/research/iee_evol/BenSulser/2D_Morpho_Stickleback/Stickleback_2021/Destination_Lakes_2021"
FISH_DIR: "/storage/research/iee_evol/BenSulser/2D_Morpho_Stickleback/Stickleback_2021/Destination_Lakes_2021"
TPS_FILE: "/storage/research/iee_evol/BenSulser/2D_Morpho_Stickleback/Stickleback_2021/Destination_Lakes_2021/Eckert_CC_CL_revised.TPS"
#OUTPUT_DIR: "/storage/scratch/iee_evol/kw23y068/Stickleback1/"
OUTPUT_DIR: "/storage/homefs/kw23y068/Master_Thesis_test/DL/"

KNN_MODEL_DIR: "/storage/homefs/kw23y068/Master_Thesis/KNN_model/"
DL_MODEL_DIR: "/storage/homefs/kw23y068/Master_Thesis/DL_model/"
